stages:
  - build
  - deploy

variables:
  VERCEL_TOKEN: pDFJHllIpAUQI7VvnuawjUY2

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0  # Sử dụng hình ảnh Docker có .NET Core SDK
  script:
    - dotnet restore
    - dotnet build

deploy:
  stage: deploy
  only:
    - master
  script:
    - vercel --token $VERCEL_TOKEN --prod
